WorkFlowSystem/Controllers/UserDocController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Runtime.Intrinsics.X86;
using System.Threading.Tasks;
using WorkFlowSystem.Models;
using WorkFlowSystem.Models.ViewModels;
using WorkFlowSystem.Repository;
using WorkFlowSystem.Services;

namespace WorkFlowSystem.Controllers
{
    public class UserDocController : BaseController
    {
        private readonly ILogger<HomeController> _logger;
        private readonly WorkflowRepository _workflow;
        private readonly WorkflowItemService _wf_item;
        private readonly DapperService _dapper;

        public UserDocController(
            ILogger<HomeController> logger,
            WorkflowRepository workflow,
            WorkflowItemService wf_item,
            DapperService dapper)
        {
            _logger = logger;
            _workflow = workflow;
            _wf_item = wf_item;
            _dapper = dapper;
        }

        public async Task<IActionResult> Index()
        {
            string username = HttpContext.Session.GetString("user.username");
            var list = await _dapper.Query("SELECT * FROM [vw_user_doc] WHERE username = @us AND sequence <> 1 ORDER BY last_date DESC", new
            {
                us = username
            });
            return View(list);
        }

        public async Task<IActionResult> DraftList()
        {
            string username = HttpContext.Session.GetString("user.username");
            var list = await _dapper.Query("SELECT * FROM [vw_user_doc] WHERE username = @us AND sequence = 1 ORDER BY last_date DESC", new
            {
                us = username
            });
            return View(list);
        }

        public async Task<IActionResult> Create()
        {
            var model = new WorkflowVM();
            model.Workflow = await _workflow.Get();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(WorkflowVM model, string btn = "submit")
        {
            string username = HttpContext.Session.GetString("user.username");
            if (!ModelState.IsValid)
            {
                model.Workflow = await _workflow.Get();
                return View(model);
            }


            var wf = await _dapper.QueryFirstOrDefaultAsync("SELECT MAX([revision_no]) AS revision_no FROM [wf_revision_history] " +
                "WHERE [workflow_no] = @wf_no AND [revision_start_date] <= GETDATE() GROUP BY [workflow_no]", new
            {
                wf_no = model.workflow_no
            });

            int sq = btn == "draft" ? 1 : 2;
            var wf_step = await _dapper.QueryFirstOrDefaultAsync("SELECT * FROM [workflow_step] " +
                "WHERE workflow_no = @wf_no AND sequence = @sq AND revision_no = @rev", new
            {
                wf_no = model.workflow_no,
                sq,
                rev = wf?.revision_no
            });
            int? step_id = wf_step?.id;

            await _dapper.Execute("INSERT INTO [workflow_item] VALUES (@wf_no, @stp, @notes, @flag, @rev, @us, " +
                "@cre, @last, @wf_item_no, @dis_flag)", new
            {
                wf_no = model.workflow_no,
                stp = wf_step?.id,
                notes = model.notes,
                flag = false,
                rev = wf_step?.revision_no,
                us = username,
                cre = DateTime.Now,
                last = DateTime.Now,
                wf_item_no = await _wf_item.GenWfItemNo(model.workflow_no),
                dis_flag = false
            }) ;

            if (btn == "draft")
                return RedirectToAction(nameof(DraftList));
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int id)
        {
            var model = new WorkflowVM();
            model.Workflow = await _workflow.Get();
            var wf_item = await _dapper.QueryFirstOrDefaultAsync("SELECT * FROM [workflow_item] WHERE id = @id", new
            {
                id = id
            });
            
            if (wf_item != null)
            {
                model.id = wf_item.id;
                model.notes = wf_item.notes;
                model.workflow_no = wf_item.workflow_no;
                model.complete_flag = wf_item.complete_flag;
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(WorkflowVM model, string btn = "submit")
        {
            string username = HttpContext.Session.GetString("user.username");
            if (!ModelState.IsValid)
            {
                model.Workflow = await _workflow.Get();
                return View(model);
            }


            var wf = await _dapper.QueryFirstOrDefaultAsync("SELECT * FROM [workflow] WHERE workflow_no = @wf_no", new
            {
                wf_no = model.workflow_no
            });

            int sq = btn == "draft" ? 1 : 2;
            var wf_step = await _dapper.QueryFirstOrDefaultAsync("SELECT * FROM [workflow_step] " +
                "WHERE workflow_no = @wf_no AND sequence = @sq AND revision_no = @rev", new
                {
                    wf_no = model.workflow_no,
                    sq,
                    rev = wf?.revision_no
                });
            int? step_id = wf_step?.id;

            await _dapper.Execute("UPDATE [workflow_item] SET workflow_no = @wf_no, step_id = @stp, notes = @notes, username = @us, last_date = @last WHERE id = @id", new
            {
                wf_no = model.workflow_no,
                stp = wf_step?.id,
                notes = model.notes,
                us = username,
                last = DateTime.Now,
                id = model.id
            });
            if (btn == "draft")
                return RedirectToAction(nameof(DraftList));
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Cancel(int id)
        {
            await _dapper.Execute("DELETE FROM [workflow_item] WHERE id = @id", new { id });
            return RedirectToAction(nameof(DraftList));
        }
    }
}

WorkFlowSystem/Views/UserDoc/Create.cshtml
@using WorkFlowSystem.Models.ViewModels;
@model WorkflowVM;
<div class="d-flex justify-content-start">
    <div>
        <a class="btn btn-sm btn-outline-dark" asp-controller="UserDoc" asp-action="Index">กลับ</a>
    </div>
</div>
<h1>แบบฟอร์มร้องขอ</h1>
<form asp-controller="UserDoc" asp-action="Create" method="post">
    <div class="row mt-4">
        <div class="col-2">
        <label>ประเภท</label>
        </div>
        <div class="col">
            <select class="form-control" asp-items="@Model.Workflow" asp-for="workflow_no">
                <option disabled selected>--- กรุณาเลือกประเภทการร้องขอ ---</option>
            </select>
        </div>
    </div>    

    <div class="row mt-3">
        <div class="col-2">
            <label>Notes</label>
        </div>
        <div class="col">
            <textarea asp-for="notes" class="form-control"></textarea>
        </div>
    </div>

    <div class="d-flex justify-content-start mt-3">
        <div>
            <button type="submit" value="draft" class="btn btn-outline-primary" name="btn">บันทึกร่าง</button>
            <button type="submit" value="submit" class="btn btn-primary" name="btn">ร้องขอ</button>
        </div>
    </div>
</form>

WorkFlowSystem/Views/UserDoc/DraftList.cshtml
@using Microsoft.AspNetCore.Http
@{
    string username = Context.Session.GetString("user.username");
}
@model IEnumerable<dynamic>

<div class="container-fluid">
    <div class="d-flex justify-content-between">
        <div>
            <h1>บันทึกแบบร่างของฉัน</h1><h2>@username</h2>
        </div>
        <div>
            <a asp-controller="UserDoc" asp-action="Create">ร้องขอ</a>
        </div>
    </div>

    @if (Model.Count() == 0)
    {
        <h2>ไม่ข้อมูลการร้องขอเร็วๆนี้</h2>
    }
    else
    {
        <div class="card p-4">
            <table class="table table-striped display" style="width: 100%">
                <thead>
                    <tr>
                        <th>Doc No.</th>
                        <th>Workflow</th>
                        <th>Notes</th>
                        <th>Step</th>
                        <th>อัปเดตล่าสุด</th>
                        <th>Action</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (var item in @Model)
                    {
                        <tr>
                            <td>@item.wf_item_no</td>
                            <td>@item.wf_name</td>
                            <td>@item.notes</td>
                            <td>
                                <small class="badge badge-secondary">(@item.sequence/@item.max_sequence)</small>
                                <p>@item.name</p>
                            </td>
                            <td>
                                @item.last_date?.ToString("dd/MM/yyyy HH:mm")
                            </td>
                            <td>
                                @if (item.sequence == 1)
                                {
                                    <a asp-controller="UserDoc" asp-action="Edit" asp-route-id="@item.id">แก้ไข</a>
                                    <a asp-controller="UserDoc" asp-action="Cancel" asp-route-id="@item.id">ยกเลิก</a>
                                }
                            </td>
                        </tr>

                    }
                </tbody>
            </table>
        </div>
    }
</div>


@section Scripts {
    <script>
        $(document).ready(function () {
            new DataTable('.table', {
                ordering: false,
            });
        });
    </script>
}

WorkFlowSystem/Views/UserDoc/Edit.cshtml
@using WorkFlowSystem.Models.ViewModels;
@model WorkflowVM;
<div class="d-flex justify-content-start">
    <div>
        <a class="btn btn-sm btn-outline-dark" asp-controller="UserDoc" asp-action="Index">กลับ</a>
    </div>
</div>
<h1>แก้ไขแบบฟอร์มร้องขอ</h1>
<form asp-controller="UserDoc" asp-action="Edit" method="post">
    <input asp-for="id" hidden />
    <div class="row mt-4">
        <div class="col-2">
            <label>ประเภท</label>
        </div>
        <div class="col">
            <select class="form-control" asp-items="@Model.Workflow" asp-for="workflow_no">
                <option disabled selected>--- กรุณาเลือกประเภทการร้องขอ ---</option>
            </select>
        </div>
    </div>

    <div class="row mt-3">
        <div class="col-2">
            <label>Notes</label>
        </div>
        <div class="col">
            <textarea asp-for="notes" class="form-control"></textarea>
        </div>
    </div>

    <div class="d-flex justify-content-start mt-3">
        <div>
            <button type="submit" value="draft" class="btn btn-outline-primary" name="btn">บันทึกร่าง</button>
            <button type="submit" value="submit" class="btn btn-primary" name="btn">ร้องขอ</button>
        </div>
    </div>
</form>

WorkFlowSystem/Views/UserDoc/Index.cshtml
@using Microsoft.AspNetCore.Http
@{
    string username = Context.Session.GetString("user.username");
}
@model IEnumerable<dynamic>

<div class="container-fluid">
    <div class="d-flex justify-content-between">
        <div>
            <h1>คำขอของฉัน</h1><h2>@username</h2>
        </div>
        <div>
            <a asp-controller="UserDoc" asp-action="Create">ร้องขอ</a>
        </div>
    </div>

    @if (Model.Count() == 0)
    {
        <h2>ไม่ข้อมูลการร้องขอเร็วๆนี้</h2>
    }
    else
    {
        <div class="card p-4">
            <table class="table table-striped display" style="width: 100%">
                <thead>
                    <tr>
                        <th>Doc No.</th>
                        <th>Workflow</th>
                        <th>Notes</th>
                        <th>Step</th>
                        <th>อัปเดตล่าสุด</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (var item in @Model)
                    {
                        <tr>
                            @if (item?.complete_flag == true)
                            {
                                <td style="border-left: 5px green solid;">@item.wf_item_no</td>
                            }
                            else if (item?.disapprove_flag == true)
                            {
                                <td style ="border-left: 5px red solid;">@item.wf_item_no</td>
                            }
                            else
                            {
                                <td>@item.wf_item_no</td>
                            }
                            <td>@item.wf_name</td>
                            <td>@item.notes</td>
                            <td>
                                @if (item?.disapprove_flag == true)
                                {
                                    <small class="badge badge-danger">(@item.sequence/@item.max_sequence)</small>
                                    <p><del>@item.name</del></p>
                                }
                                else if (item?.complete_flag == true)
                                {
                                    <small class="badge badge-success">(@item.sequence/@item.max_sequence)</small>
                                    <p>@item.name</p>
                                }
                                else
                                {
                                    <small class="badge badge-warning">(@item.sequence/@item.max_sequence)</small>
                                    <p>@item.name</p>
                                }
                            </td>
                            <td>
                                @item.last_date?.ToString("dd/MM/yyyy HH:mm")
                            </td>
                        </tr>

                    }
                </tbody>
            </table>
        </div>
    }
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            new DataTable('.table', {
                ordering: false,
            });
        });
    </script>
}