WorkFlowSystem/Controllers/DocController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Threading.Tasks;
using WorkFlowSystem.Models.ViewModels;
using WorkFlowSystem.Repository;
using WorkFlowSystem.Services;

namespace WorkFlowSystem.Controllers
{
    public class DocController : BaseController
    {
        private readonly ILogger<HomeController> _logger;
        private readonly WorkflowRepository _workflow;
        private readonly DapperService _dapper;
        private readonly ApproveRepository _approve;

        public DocController(
            ILogger<HomeController> logger,
            WorkflowRepository workflow,
            DapperService dapper,
            ApproveRepository approve)
        {
            _logger = logger;
            _workflow = workflow;
            _dapper = dapper;
            _approve = approve;
        }

        public async Task<IActionResult> RequestList()
        {
            string role_no = HttpContext.Session.GetString("user.role_no");
            string department_no = HttpContext.Session.GetString("user.department_no");
            var list = await _dapper.Query("SELECT * FROM [vw_user_doc] " +
                "WHERE department_no = @dep AND role_no = @rol AND disapprove_flag = 0" +
                "ORDER BY last_date ASC", new
            {
                dep = department_no,
                rol = role_no
            });
            return View(list);
        }

        public async Task<IActionResult> Detail(int id)
        {
            var wf_item = await _dapper.QueryFirstOrDefaultAsync("SELECT * FROM [vw_user_doc] WHERE id = @id", new
            {
                id = id
            });
            return View(wf_item);
        }

        public async Task<IActionResult> Approve(int id)
        {
            string username = HttpContext.Session.GetString("user.username");
            var wf_item = await _dapper.QueryFirstOrDefaultAsync("SELECT * FROM [vw_user_doc] WHERE id = @id", new
            {
                id = id
            });

            var wf_step_current = await _dapper.QueryFirstOrDefaultAsync("SELECT * FROM [workflow_step] " +
                "WHERE workflow_no = @wf_no AND id = @id", new
                {
                    wf_no = wf_item.workflow_no,
                    id = wf_item.step_id
                });

            var wf_step_next = await _dapper.QueryFirstOrDefaultAsync("SELECT * FROM [workflow_step] " +
                "WHERE workflow_no = @wf_no AND sequence = @sq AND revision_no = @rev", new
                {
                    wf_no = wf_item.workflow_no,
                    sq = wf_step_current.sequence + 1,
                    rev = wf_item.step_revision_no
                });

            // IS LAST STEP
            bool isLast = await checkIsLastStep(wf_step_next.id);

            // UPDATE ITEM STEP
            await _dapper.Execute("UPDATE [workflow_item] SET complete_flag = @flag, step_id = @stp, last_date = @last WHERE id = @id", new
            {
                flag = isLast,
                stp = wf_step_next.id,
                id = wf_item.id,
                last = DateTime.Now,
            });

            // SAVE HISTORY APPROVE
            await _dapper.Execute("INSERT INTO [wf_item_history] VALUES (@item_id, @stp, @user, @date, @act, @remarks)", new
            {
                item_id = wf_item.id,
                stp = wf_step_current.id,
                user = username,
                date = DateTime.Now,
                act = "APV",
                remarks = ""
            });
            return RedirectToAction(nameof(RequestList));
        }

        private async Task<bool> checkIsLastStep(dynamic id)
        {
            var wf_step = await _dapper.QueryFirstOrDefaultAsync("SELECT * FROM [workflow_step] WHERE id = @id", new { id });
            var wf_step_next = await _dapper.QueryFirstOrDefaultAsync("SELECT * FROM [workflow_step] WHERE " +
                "revision_no = @rev AND sequence = @seq AND workflow_no = @wf_no", new {
                rev = wf_step.revision_no,
                seq = wf_step.sequence + 1,
                wf_no = wf_step.workflow_no
            });
            return wf_step_next == null;
        }

        [HttpPost]
        public async Task<IActionResult> Disapprove([FromForm] DisapproveVM model)
        {
            string username = HttpContext.Session.GetString("user.username");

            var wf_item = await _dapper.QueryFirstOrDefaultAsync("SELECT * FROM [workflow_item] WHERE id = @id", new
            {
                id = model.id
            });

            await _dapper.Execute("INSERT INTO [wf_item_history] VALUES (@id, @stp, @us, @date, @act, @remarks)", new
            {
                id = model.id,
                stp = wf_item.step_id,
                us = username,
                date = DateTime.Now,
                act = "DIS",
                remarks = model.remarks
            });

            await _dapper.Execute("UPDATE [workflow_item] SET disapprove_flag = @flag, last_date = @date WHERE id = @id", new
            {
                flag = true,
                date = DateTime.Now,
                id = model.id
            });
            return RedirectToAction(nameof(RequestList));
        }
        
    }
}

WorkFlowSystem/Controllers/LoginController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;
using WorkFlowSystem.Models.ViewModels;
using WorkFlowSystem.Services;

namespace WorkFlowSystem.Controllers
{
    public class LoginController : BaseController
    {
        private readonly DapperService _dapper;

        public LoginController(DapperService dapper)
        {
            _dapper = dapper;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Index(LoginVM model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = await _dapper.QueryFirstOrDefaultAsync("SELECT * FROM [user] WHERE username = @username AND password = @password", 
                new { username = model.username, password = model.password });
            if(user != null)
            {
                setUser(user.username, user.role_no, user.department_no);
                return RedirectToAction("Index", "UserDoc");
            }
            else
            {
                TempData["username-error"] = "ชื่อผู้ใช้งาน หรือรหัสผิด";
                return View(model);
            }
        }

        public async Task<IActionResult> Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction(nameof(Index));
        }

        private void setUser(string username, string role_no, string dept_no)
        {
            HttpContext.Session.SetString("user.username", username);
            HttpContext.Session.SetString("user.role_no", role_no);
            HttpContext.Session.SetString("user.department_no", dept_no);
        }
    }
}

WorkFlowSystem/Controllers/StepController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Security.Cryptography;
using System.Threading.Tasks;
using WorkFlowSystem.Models;
using WorkFlowSystem.Models.ViewModels;
using WorkFlowSystem.Repository;
using WorkFlowSystem.Services;

namespace WorkFlowSystem.Controllers
{
    public class StepController : BaseController
    {
        private readonly DapperService _dapper;
        private readonly DropdownService _dropdown;
        private readonly StepRepository _step;

        public StepController(
            DapperService dapper,
            DropdownService dropdown,
			StepRepository step)
        {
            _dapper = dapper;
            _dropdown = dropdown;
            _step = step;
        }
        public async Task<IActionResult> Index()
        {
            var step = await _dapper.Query("SELECT * FROM [vw_wf_step]");
            return View(step);
        }

        public async Task<IActionResult> StepList(string wf, int rev)
        {
            var step = await _dapper.Query("SELECT * FROM [vw_wf_step_list] " +
                "WHERE workflow_no = @wf AND revision_no = @rev " +
                "ORDER BY sequence ASC", new
                {
                    wf,
                    rev
                });

            int max_rev = await _step.GetMaxRevByWf(wf);

            SteplistVM model = new SteplistVM()
            {
                list = step,
                max_revision = max_rev
            };
            return View(model);
        }

        public async Task<IActionResult> EditStepList(string wf, int rev)
        {
            var step = await _dapper.Query("SELECT * FROM [workflow_step] " +
                "WHERE workflow_no = @wf AND revision_no = @rev", new
            {
                wf,
                rev
            });

            EditStepListVM model = new EditStepListVM();
            foreach(var item in step)
            {
				model.list.Add(new Vw_wf_step_list() {
					id = item.id,
					name = item.name,
					workflow_no = item.workflow_no,
					revision_no = item.revision_no,
					role_no = item.role_no,
					department_no = item.department_no,
					role_name = item.role_name,
					department_name = item.department_name,
					sequence = item.sequence,
					wf_name = item.wf_name
				});
			}
            
            model.department = await _dropdown.Department();
            model.role = await _dropdown.Role();
            return View(model);
        }

		[HttpPost]
		public async Task<IActionResult> SaveStep(List<SaveStepVM> list)
		{
			try
			{
                string username = HttpContext.Session.GetString("user.username");
                if (await CheckIsChange(list) == true)
                {
                    int max_rev = await _step.GetMaxRevByWf(list.First().workflow_no);
                    await _step.Insert(list, max_rev, username);
                    return Json(new { success = true, text = "เพิ่ม Revision ใหม่สำเร็จ" });
                }
                return Json(new { success = true, text = "ไม่มีการเปลี่ยนแปลง" });
            }
			catch (Exception ex)
			{
                return Json(new { success = false, text = "เกิดข้อผิดพลาด : " + ex.Message });
            }
		}

		private async Task<bool> CheckIsChange(List<SaveStepVM> list)
		{
			if (list.Count == 0)
				return false;

			var old_step = await _dapper.Query("SELECT * FROM [workflow_step] WHERE workflow_no = @wf AND revision_no = @rev", new
			{
				wf = list.First().workflow_no,
				rev = list.First().revision_no
			});

			// Check count
			// +2 for draft and approve
			if (old_step.Count() != (list.Count() + 2))
			{
				return true;
			}

			// Check content
			// not compare draft and approve
			int i = -1;
			foreach (var item in old_step)
			{
				i++;
				if (i == 0)
					continue;

				if (i + 1 == old_step.Count())
					break;

				if (item.name != list[i - 1].name ||
					item.role_no != list[i - 1].role_no ||
					item.department_no != list[i - 1].department_no)
					return true;

			}

			return false;
		}

	}
}

WorkFlowSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WorkFlowSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.3/css/dataTables.dataTables.css" />
</head>
<body>
    @using Microsoft.AspNetCore.Http
    @{
        string role_no = Context.Session.GetString("user.role_no");
    }

    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Smart WorkFlow</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                ตรวจสอบคำร้อง
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" asp-controller="UserDoc" asp-action="Index">คำร้องของฉัน</a>
                                <a class="dropdown-item" asp-controller="UserDoc" asp-action="DraftList">บันทึกแบบร่าง</a>
                            </div>
                        </li>
                    </ul>
                    @if (role_no != "EMP")
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Doc" asp-action="RequestList">ที่ต้องอนุมัติ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Step" asp-action="Index">สายอนุมัติ</a>
                        </li>
                    }
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <a asp-controller="Login" asp-action="Logout">ออกจากระบบ</a>
                </form>
            </div>
        </nav>
        
    </header>
    <div class="container-fluid" style="max-width: 1600px;">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2567 - WorkFlowSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/2.0.3/js/dataTables.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

WorkFlowSystem/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WorkFlowSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.3/css/dataTables.dataTables.css"></link>
</head>
<body>
    <div class="container-fluid" style="max-width: 1600px;">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2567 - WorkFlowSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/2.0.3/js/dataTables.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>